import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import GoogleAnalyticsScript from "./GoogleAnalyticsScript";
import NavBar from "./NavBar";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	openGraph: {
		title: "...",
		description: "...",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" data-theme="sunset">
			<GoogleAnalyticsScript />
			<body className={roboto.className}>
				<SessionProvider>
					<NavBar />
					<main className="p-5">{children}</main>
				</SessionProvider>
			</body>
		</html>
	);
}
